// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9OUFgsWXfgxNzoNWRKMMgOHjEG1N2LQk',
    appId: '1:483954936238:web:ef6bf34a5192b507b5a03f',
    messagingSenderId: '483954936238',
    projectId: 'supergym-4a47d',
    authDomain: 'supergym-4a47d.firebaseapp.com',
    storageBucket: 'supergym-4a47d.appspot.com',
    measurementId: 'G-FRP0WB0LMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw6bT6P9dQtlhtRNUrJvOiXvCua8GJA9s',
    appId: '1:483954936238:android:9ee8acf11e4749b1b5a03f',
    messagingSenderId: '483954936238',
    projectId: 'supergym-4a47d',
    storageBucket: 'supergym-4a47d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLZc8k2T9df5mEBWpw0tikYcCIKSvkymo',
    appId: '1:483954936238:ios:a9bbefbace63933cb5a03f',
    messagingSenderId: '483954936238',
    projectId: 'supergym-4a47d',
    storageBucket: 'supergym-4a47d.appspot.com',
    iosBundleId: 'com.example.flutterGym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLZc8k2T9df5mEBWpw0tikYcCIKSvkymo',
    appId: '1:483954936238:ios:a9b22d3bf76b6576b5a03f',
    messagingSenderId: '483954936238',
    projectId: 'supergym-4a47d',
    storageBucket: 'supergym-4a47d.appspot.com',
    iosBundleId: 'com.example.flutterGym.RunnerTests',
  );
}
